### ISSUE TITLE
Changes needed for Skynet Explore Phase Leaderboard Scraper

### ISSUE THREAD

**Issue by dghelm** [jordanpinski/giphyaf#1]
https://github.com/jordanpinski/giphyaf/blob/42b55913a6c0c4d7988a70c361dfd22587e35220/src/skynet.tsx#L96

Notice user content wasn't getting scraped by our Leaderboard scraper. If you want to participate (🤞) with the Feed DAC, we need the items to follow the Post interface.

Per PJ, right now we're scraping objects like this:
```
{
  timestamp: 1619542148,
  json: {
    image: {
      ext: 'image/gif',
      url: 'https://siasky.net/_AY8i8fsryOJqWb-k_Jg-lDyoKkDwxxgYMAWTLEEIYhTOg'
    },
    title: 'CyberSpace',
    tags: [ 'internet' ]
  },
  metadata: { action: 'created' }
}
```

but we need a valid `skylink` and `id` field (not undefined) to properly scrape the item.

The "skylink" format here is pretty broad -- I think ideally `sia://[skylink]` but we actually will accept anything that passes this regex:
```const indexRegexp = /^(.*[\/:])?(?<skylink>[a-zA-Z0-9-_]{46})\/?$/;
  const matchResult = skylinkRaw.match(indexRegexp)
  if (!matchResult || !matchResult.groups) {
    return ""
  }
  return matchResult.groups.skylink
  ```

**Comment by dghelm** [comment]
I think I misdiagnosed this -- I think the main issue for using the Feed DAC is actually an out-of-date library.

**Comment by jordanpinski** [comment]
Thanks for looking into that - I've updated the Feed DAC library to 0.2.2
